version: '3'

services:
  frontend:
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment: 
      - CHOKIDAR_USEPOLLING=true  #- перенёс в package.json 

  api: 
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src