version: '3'

services:

  frontend:
    build: ./frontend
    container_name: rwd-front
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment: 
      - CHOKIDAR_USEPOLLING=true  #- перенёс в package.json 

  api:
    build: ./api
    container_name: rwd-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/rwd_app
    depends_on:
      - api_db
  
  auth:
    build: ./auth
    container_name: rwd-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/rwd_auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: rwd-api-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: rwd-auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:


  