version: '3'

services:

  frontend:
    build: ./frontend
    container_name: rwd-front
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - rwd-network

  api:
    build: ./api
    container_name: rwd-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/rwd_app
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - rwd-network 

  auth:
    build: ./auth
    container_name: rwd-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/rwd_auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - rwd-network

  api_db:
    image: mongo:latest
    container_name: rwd-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - rwd-network

  auth_db:
    image: mongo:latest
    container_name: rwd-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - rwd-network

  nginx:
    image: nginx:stable-alpine
    container_name: rwd-nginx
    ports:
      - "80:80"
    volumes:
      # - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - rwd-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  rwd-network:
    driver: bridge